/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    news: News;
    achievements: Achievement;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    achievements: AchievementsSelect<false> | AchievementsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    headerNav: HeaderNav;
    footerNav: FooterNav;
    footerContent: FooterContent;
    homeSlider: HomeSlider;
  };
  globalsSelect: {
    headerNav: HeaderNavSelect<false> | HeaderNavSelect<true>;
    footerNav: FooterNavSelect<false> | FooterNavSelect<true>;
    footerContent: FooterContentSelect<false> | FooterContentSelect<true>;
    homeSlider: HomeSliderSelect<false> | HomeSliderSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  blocks?:
    | (
        | {
            heading: string;
            subtitle?: string | null;
            /**
             * Если задан — используется upload; иначе берётся URL ниже.
             */
            image?: (number | null) | Media;
            /**
             * Прямой URL (например, на detskiydomuss.ru).
             */
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            image?: (number | null) | Media;
            /**
             * Альтернатива upload — прямой URL.
             */
            imageUrl?: string | null;
            alt?: string | null;
            href?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'banner';
          }
        | {
            title: string;
            text?: string | null;
            buttonLabel?: string | null;
            buttonUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cta';
          }
        | {
            slides?:
              | {
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  alt?: string | null;
                  href?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'slider';
          }
        | {
            body: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'content';
          }
        | {
            media?: (number | null) | Media;
            imageUrl?: string | null;
            alt?: string | null;
            caption?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            title: string;
            intro?: string | null;
            tabs?: ('help_request' | 'want_to_help' | 'feedback')[] | null;
            privacyHref?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'formTabs';
          }
        | {
            text: string;
            /**
             * Без решётки, латиницей. Используется для ссылок вида /info#main, /socials#living и т.п.
             */
            anchorId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'heading';
          }
        | {
            sectionTitle: string;
            items?:
              | {
                  title: string;
                  file?: (number | null) | Media;
                  /**
                   * Альтернатива upload — прямой URL.
                   */
                  fileUrl?: string | null;
                  fileExt?: ('pdf' | 'docx' | 'doc' | 'xlsx' | 'xls' | 'zip' | 'other') | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'fileList';
          }
        | {
            title?: string | null;
            /**
             * Вставится «как есть». Используется для виджетов Госуслуг, форм CF7 и т.п.
             */
            html: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
        | {
            title?: string | null;
            source: 'achievements' | 'custom';
            year?: number | null;
            items?:
              | {
                  image?: (number | null) | Media;
                  imageUrl?: string | null;
                  alt?: string | null;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Содержимое слайдера редактируется в глобале «Главный слайдер». Здесь — место для размещения.
             */
            note?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'homeSlider';
          }
        | {
            title?: string | null;
            subtitle?: string | null;
            columns: '1' | '2' | '3' | '4' | '5' | '6';
            column1?:
              | (
                  | {
                      heading: string;
                      subtitle?: string | null;
                      /**
                       * Если задан — используется upload; иначе берётся URL ниже.
                       */
                      image?: (number | null) | Media;
                      /**
                       * Прямой URL (например, на detskiydomuss.ru).
                       */
                      imageUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'hero';
                    }
                  | {
                      image?: (number | null) | Media;
                      /**
                       * Альтернатива upload — прямой URL.
                       */
                      imageUrl?: string | null;
                      alt?: string | null;
                      href?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'banner';
                    }
                  | {
                      title: string;
                      text?: string | null;
                      buttonLabel?: string | null;
                      buttonUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta';
                    }
                  | {
                      slides?:
                        | {
                            image?: (number | null) | Media;
                            imageUrl?: string | null;
                            alt?: string | null;
                            href?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'slider';
                    }
                  | {
                      body: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'content';
                    }
                  | {
                      media?: (number | null) | Media;
                      imageUrl?: string | null;
                      alt?: string | null;
                      caption?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'image';
                    }
                  | {
                      title: string;
                      intro?: string | null;
                      tabs?: ('help_request' | 'want_to_help' | 'feedback')[] | null;
                      privacyHref?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'formTabs';
                    }
                  | {
                      text: string;
                      /**
                       * Без решётки, латиницей. Используется для ссылок вида /info#main, /socials#living и т.п.
                       */
                      anchorId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heading';
                    }
                  | {
                      sectionTitle: string;
                      items?:
                        | {
                            title: string;
                            file?: (number | null) | Media;
                            /**
                             * Альтернатива upload — прямой URL.
                             */
                            fileUrl?: string | null;
                            fileExt?: ('pdf' | 'docx' | 'doc' | 'xlsx' | 'xls' | 'zip' | 'other') | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'fileList';
                    }
                  | {
                      title?: string | null;
                      /**
                       * Вставится «как есть». Используется для виджетов Госуслуг, форм CF7 и т.п.
                       */
                      html: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'embed';
                    }
                )[]
              | null;
            column2?:
              | (
                  | {
                      heading: string;
                      subtitle?: string | null;
                      /**
                       * Если задан — используется upload; иначе берётся URL ниже.
                       */
                      image?: (number | null) | Media;
                      /**
                       * Прямой URL (например, на detskiydomuss.ru).
                       */
                      imageUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'hero';
                    }
                  | {
                      image?: (number | null) | Media;
                      /**
                       * Альтернатива upload — прямой URL.
                       */
                      imageUrl?: string | null;
                      alt?: string | null;
                      href?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'banner';
                    }
                  | {
                      title: string;
                      text?: string | null;
                      buttonLabel?: string | null;
                      buttonUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta';
                    }
                  | {
                      slides?:
                        | {
                            image?: (number | null) | Media;
                            imageUrl?: string | null;
                            alt?: string | null;
                            href?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'slider';
                    }
                  | {
                      body: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'content';
                    }
                  | {
                      media?: (number | null) | Media;
                      imageUrl?: string | null;
                      alt?: string | null;
                      caption?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'image';
                    }
                  | {
                      title: string;
                      intro?: string | null;
                      tabs?: ('help_request' | 'want_to_help' | 'feedback')[] | null;
                      privacyHref?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'formTabs';
                    }
                  | {
                      text: string;
                      /**
                       * Без решётки, латиницей. Используется для ссылок вида /info#main, /socials#living и т.п.
                       */
                      anchorId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heading';
                    }
                  | {
                      sectionTitle: string;
                      items?:
                        | {
                            title: string;
                            file?: (number | null) | Media;
                            /**
                             * Альтернатива upload — прямой URL.
                             */
                            fileUrl?: string | null;
                            fileExt?: ('pdf' | 'docx' | 'doc' | 'xlsx' | 'xls' | 'zip' | 'other') | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'fileList';
                    }
                  | {
                      title?: string | null;
                      /**
                       * Вставится «как есть». Используется для виджетов Госуслуг, форм CF7 и т.п.
                       */
                      html: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'embed';
                    }
                )[]
              | null;
            column3?:
              | (
                  | {
                      heading: string;
                      subtitle?: string | null;
                      /**
                       * Если задан — используется upload; иначе берётся URL ниже.
                       */
                      image?: (number | null) | Media;
                      /**
                       * Прямой URL (например, на detskiydomuss.ru).
                       */
                      imageUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'hero';
                    }
                  | {
                      image?: (number | null) | Media;
                      /**
                       * Альтернатива upload — прямой URL.
                       */
                      imageUrl?: string | null;
                      alt?: string | null;
                      href?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'banner';
                    }
                  | {
                      title: string;
                      text?: string | null;
                      buttonLabel?: string | null;
                      buttonUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta';
                    }
                  | {
                      slides?:
                        | {
                            image?: (number | null) | Media;
                            imageUrl?: string | null;
                            alt?: string | null;
                            href?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'slider';
                    }
                  | {
                      body: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'content';
                    }
                  | {
                      media?: (number | null) | Media;
                      imageUrl?: string | null;
                      alt?: string | null;
                      caption?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'image';
                    }
                  | {
                      title: string;
                      intro?: string | null;
                      tabs?: ('help_request' | 'want_to_help' | 'feedback')[] | null;
                      privacyHref?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'formTabs';
                    }
                  | {
                      text: string;
                      /**
                       * Без решётки, латиницей. Используется для ссылок вида /info#main, /socials#living и т.п.
                       */
                      anchorId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heading';
                    }
                  | {
                      sectionTitle: string;
                      items?:
                        | {
                            title: string;
                            file?: (number | null) | Media;
                            /**
                             * Альтернатива upload — прямой URL.
                             */
                            fileUrl?: string | null;
                            fileExt?: ('pdf' | 'docx' | 'doc' | 'xlsx' | 'xls' | 'zip' | 'other') | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'fileList';
                    }
                  | {
                      title?: string | null;
                      /**
                       * Вставится «как есть». Используется для виджетов Госуслуг, форм CF7 и т.п.
                       */
                      html: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'embed';
                    }
                )[]
              | null;
            column4?:
              | (
                  | {
                      heading: string;
                      subtitle?: string | null;
                      /**
                       * Если задан — используется upload; иначе берётся URL ниже.
                       */
                      image?: (number | null) | Media;
                      /**
                       * Прямой URL (например, на detskiydomuss.ru).
                       */
                      imageUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'hero';
                    }
                  | {
                      image?: (number | null) | Media;
                      /**
                       * Альтернатива upload — прямой URL.
                       */
                      imageUrl?: string | null;
                      alt?: string | null;
                      href?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'banner';
                    }
                  | {
                      title: string;
                      text?: string | null;
                      buttonLabel?: string | null;
                      buttonUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta';
                    }
                  | {
                      slides?:
                        | {
                            image?: (number | null) | Media;
                            imageUrl?: string | null;
                            alt?: string | null;
                            href?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'slider';
                    }
                  | {
                      body: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'content';
                    }
                  | {
                      media?: (number | null) | Media;
                      imageUrl?: string | null;
                      alt?: string | null;
                      caption?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'image';
                    }
                  | {
                      title: string;
                      intro?: string | null;
                      tabs?: ('help_request' | 'want_to_help' | 'feedback')[] | null;
                      privacyHref?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'formTabs';
                    }
                  | {
                      text: string;
                      /**
                       * Без решётки, латиницей. Используется для ссылок вида /info#main, /socials#living и т.п.
                       */
                      anchorId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heading';
                    }
                  | {
                      sectionTitle: string;
                      items?:
                        | {
                            title: string;
                            file?: (number | null) | Media;
                            /**
                             * Альтернатива upload — прямой URL.
                             */
                            fileUrl?: string | null;
                            fileExt?: ('pdf' | 'docx' | 'doc' | 'xlsx' | 'xls' | 'zip' | 'other') | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'fileList';
                    }
                  | {
                      title?: string | null;
                      /**
                       * Вставится «как есть». Используется для виджетов Госуслуг, форм CF7 и т.п.
                       */
                      html: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'embed';
                    }
                )[]
              | null;
            column5?:
              | (
                  | {
                      heading: string;
                      subtitle?: string | null;
                      /**
                       * Если задан — используется upload; иначе берётся URL ниже.
                       */
                      image?: (number | null) | Media;
                      /**
                       * Прямой URL (например, на detskiydomuss.ru).
                       */
                      imageUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'hero';
                    }
                  | {
                      image?: (number | null) | Media;
                      /**
                       * Альтернатива upload — прямой URL.
                       */
                      imageUrl?: string | null;
                      alt?: string | null;
                      href?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'banner';
                    }
                  | {
                      title: string;
                      text?: string | null;
                      buttonLabel?: string | null;
                      buttonUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta';
                    }
                  | {
                      slides?:
                        | {
                            image?: (number | null) | Media;
                            imageUrl?: string | null;
                            alt?: string | null;
                            href?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'slider';
                    }
                  | {
                      body: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'content';
                    }
                  | {
                      media?: (number | null) | Media;
                      imageUrl?: string | null;
                      alt?: string | null;
                      caption?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'image';
                    }
                  | {
                      title: string;
                      intro?: string | null;
                      tabs?: ('help_request' | 'want_to_help' | 'feedback')[] | null;
                      privacyHref?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'formTabs';
                    }
                  | {
                      text: string;
                      /**
                       * Без решётки, латиницей. Используется для ссылок вида /info#main, /socials#living и т.п.
                       */
                      anchorId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heading';
                    }
                  | {
                      sectionTitle: string;
                      items?:
                        | {
                            title: string;
                            file?: (number | null) | Media;
                            /**
                             * Альтернатива upload — прямой URL.
                             */
                            fileUrl?: string | null;
                            fileExt?: ('pdf' | 'docx' | 'doc' | 'xlsx' | 'xls' | 'zip' | 'other') | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'fileList';
                    }
                  | {
                      title?: string | null;
                      /**
                       * Вставится «как есть». Используется для виджетов Госуслуг, форм CF7 и т.п.
                       */
                      html: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'embed';
                    }
                )[]
              | null;
            column6?:
              | (
                  | {
                      heading: string;
                      subtitle?: string | null;
                      /**
                       * Если задан — используется upload; иначе берётся URL ниже.
                       */
                      image?: (number | null) | Media;
                      /**
                       * Прямой URL (например, на detskiydomuss.ru).
                       */
                      imageUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'hero';
                    }
                  | {
                      image?: (number | null) | Media;
                      /**
                       * Альтернатива upload — прямой URL.
                       */
                      imageUrl?: string | null;
                      alt?: string | null;
                      href?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'banner';
                    }
                  | {
                      title: string;
                      text?: string | null;
                      buttonLabel?: string | null;
                      buttonUrl?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'cta';
                    }
                  | {
                      slides?:
                        | {
                            image?: (number | null) | Media;
                            imageUrl?: string | null;
                            alt?: string | null;
                            href?: string | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'slider';
                    }
                  | {
                      body: {
                        root: {
                          type: string;
                          children: {
                            type: any;
                            version: number;
                            [k: string]: unknown;
                          }[];
                          direction: ('ltr' | 'rtl') | null;
                          format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                          indent: number;
                          version: number;
                        };
                        [k: string]: unknown;
                      };
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'content';
                    }
                  | {
                      media?: (number | null) | Media;
                      imageUrl?: string | null;
                      alt?: string | null;
                      caption?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'image';
                    }
                  | {
                      title: string;
                      intro?: string | null;
                      tabs?: ('help_request' | 'want_to_help' | 'feedback')[] | null;
                      privacyHref?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'formTabs';
                    }
                  | {
                      text: string;
                      /**
                       * Без решётки, латиницей. Используется для ссылок вида /info#main, /socials#living и т.п.
                       */
                      anchorId?: string | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'heading';
                    }
                  | {
                      sectionTitle: string;
                      items?:
                        | {
                            title: string;
                            file?: (number | null) | Media;
                            /**
                             * Альтернатива upload — прямой URL.
                             */
                            fileUrl?: string | null;
                            fileExt?: ('pdf' | 'docx' | 'doc' | 'xlsx' | 'xls' | 'zip' | 'other') | null;
                            id?: string | null;
                          }[]
                        | null;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'fileList';
                    }
                  | {
                      title?: string | null;
                      /**
                       * Вставится «как есть». Используется для виджетов Госуслуг, форм CF7 и т.п.
                       */
                      html: string;
                      id?: string | null;
                      blockName?: string | null;
                      blockType: 'embed';
                    }
                )[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'container';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  title: string;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  publishedAt: string;
  /**
   * Используется для карточки в ленте.
   */
  thumbnail?: (number | null) | Media;
  /**
   * Альтернатива upload — прямой URL.
   */
  thumbnailUrl?: string | null;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Альтернатива — массив прямых URL изображений.
   */
  galleryUrls?:
    | {
        url: string;
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements".
 */
export interface Achievement {
  id: number;
  /**
   * Сортировка в галерее (1, 2, 3, ...).
   */
  order: number;
  /**
   * Можно оставить пустым или поставить «1», «2», ...
   */
  title?: string | null;
  year?: number | null;
  image?: (number | null) | Media;
  /**
   * Альтернатива upload — прямой URL.
   */
  imageUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Заявки с публичных форм сайта (без отправки email — оператор обрабатывает вручную).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  formType: 'help_request' | 'want_to_help' | 'feedback';
  name: string;
  phone?: string | null;
  email?: string | null;
  subject?: string | null;
  message: string;
  pageSlug?: string | null;
  status: 'new' | 'in_progress' | 'done';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'achievements';
        value: number | Achievement;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subtitle?: T;
              image?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        banner?:
          | T
          | {
              image?: T;
              imageUrl?: T;
              alt?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
        cta?:
          | T
          | {
              title?: T;
              text?: T;
              buttonLabel?: T;
              buttonUrl?: T;
              id?: T;
              blockName?: T;
            };
        slider?:
          | T
          | {
              slides?:
                | T
                | {
                    image?: T;
                    imageUrl?: T;
                    alt?: T;
                    href?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        content?:
          | T
          | {
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              media?: T;
              imageUrl?: T;
              alt?: T;
              caption?: T;
              id?: T;
              blockName?: T;
            };
        formTabs?:
          | T
          | {
              title?: T;
              intro?: T;
              tabs?: T;
              privacyHref?: T;
              id?: T;
              blockName?: T;
            };
        heading?:
          | T
          | {
              text?: T;
              anchorId?: T;
              id?: T;
              blockName?: T;
            };
        fileList?:
          | T
          | {
              sectionTitle?: T;
              items?:
                | T
                | {
                    title?: T;
                    file?: T;
                    fileUrl?: T;
                    fileExt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              title?: T;
              html?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              title?: T;
              source?: T;
              year?: T;
              items?:
                | T
                | {
                    image?: T;
                    imageUrl?: T;
                    alt?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        homeSlider?:
          | T
          | {
              note?: T;
              id?: T;
              blockName?: T;
            };
        container?:
          | T
          | {
              title?: T;
              subtitle?: T;
              columns?: T;
              column1?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          heading?: T;
                          subtitle?: T;
                          image?: T;
                          imageUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    banner?:
                      | T
                      | {
                          image?: T;
                          imageUrl?: T;
                          alt?: T;
                          href?: T;
                          id?: T;
                          blockName?: T;
                        };
                    cta?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                          buttonLabel?: T;
                          buttonUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    slider?:
                      | T
                      | {
                          slides?:
                            | T
                            | {
                                image?: T;
                                imageUrl?: T;
                                alt?: T;
                                href?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    content?:
                      | T
                      | {
                          body?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          media?: T;
                          imageUrl?: T;
                          alt?: T;
                          caption?: T;
                          id?: T;
                          blockName?: T;
                        };
                    formTabs?:
                      | T
                      | {
                          title?: T;
                          intro?: T;
                          tabs?: T;
                          privacyHref?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heading?:
                      | T
                      | {
                          text?: T;
                          anchorId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    fileList?:
                      | T
                      | {
                          sectionTitle?: T;
                          items?:
                            | T
                            | {
                                title?: T;
                                file?: T;
                                fileUrl?: T;
                                fileExt?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    embed?:
                      | T
                      | {
                          title?: T;
                          html?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              column2?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          heading?: T;
                          subtitle?: T;
                          image?: T;
                          imageUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    banner?:
                      | T
                      | {
                          image?: T;
                          imageUrl?: T;
                          alt?: T;
                          href?: T;
                          id?: T;
                          blockName?: T;
                        };
                    cta?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                          buttonLabel?: T;
                          buttonUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    slider?:
                      | T
                      | {
                          slides?:
                            | T
                            | {
                                image?: T;
                                imageUrl?: T;
                                alt?: T;
                                href?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    content?:
                      | T
                      | {
                          body?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          media?: T;
                          imageUrl?: T;
                          alt?: T;
                          caption?: T;
                          id?: T;
                          blockName?: T;
                        };
                    formTabs?:
                      | T
                      | {
                          title?: T;
                          intro?: T;
                          tabs?: T;
                          privacyHref?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heading?:
                      | T
                      | {
                          text?: T;
                          anchorId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    fileList?:
                      | T
                      | {
                          sectionTitle?: T;
                          items?:
                            | T
                            | {
                                title?: T;
                                file?: T;
                                fileUrl?: T;
                                fileExt?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    embed?:
                      | T
                      | {
                          title?: T;
                          html?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              column3?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          heading?: T;
                          subtitle?: T;
                          image?: T;
                          imageUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    banner?:
                      | T
                      | {
                          image?: T;
                          imageUrl?: T;
                          alt?: T;
                          href?: T;
                          id?: T;
                          blockName?: T;
                        };
                    cta?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                          buttonLabel?: T;
                          buttonUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    slider?:
                      | T
                      | {
                          slides?:
                            | T
                            | {
                                image?: T;
                                imageUrl?: T;
                                alt?: T;
                                href?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    content?:
                      | T
                      | {
                          body?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          media?: T;
                          imageUrl?: T;
                          alt?: T;
                          caption?: T;
                          id?: T;
                          blockName?: T;
                        };
                    formTabs?:
                      | T
                      | {
                          title?: T;
                          intro?: T;
                          tabs?: T;
                          privacyHref?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heading?:
                      | T
                      | {
                          text?: T;
                          anchorId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    fileList?:
                      | T
                      | {
                          sectionTitle?: T;
                          items?:
                            | T
                            | {
                                title?: T;
                                file?: T;
                                fileUrl?: T;
                                fileExt?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    embed?:
                      | T
                      | {
                          title?: T;
                          html?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              column4?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          heading?: T;
                          subtitle?: T;
                          image?: T;
                          imageUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    banner?:
                      | T
                      | {
                          image?: T;
                          imageUrl?: T;
                          alt?: T;
                          href?: T;
                          id?: T;
                          blockName?: T;
                        };
                    cta?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                          buttonLabel?: T;
                          buttonUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    slider?:
                      | T
                      | {
                          slides?:
                            | T
                            | {
                                image?: T;
                                imageUrl?: T;
                                alt?: T;
                                href?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    content?:
                      | T
                      | {
                          body?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          media?: T;
                          imageUrl?: T;
                          alt?: T;
                          caption?: T;
                          id?: T;
                          blockName?: T;
                        };
                    formTabs?:
                      | T
                      | {
                          title?: T;
                          intro?: T;
                          tabs?: T;
                          privacyHref?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heading?:
                      | T
                      | {
                          text?: T;
                          anchorId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    fileList?:
                      | T
                      | {
                          sectionTitle?: T;
                          items?:
                            | T
                            | {
                                title?: T;
                                file?: T;
                                fileUrl?: T;
                                fileExt?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    embed?:
                      | T
                      | {
                          title?: T;
                          html?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              column5?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          heading?: T;
                          subtitle?: T;
                          image?: T;
                          imageUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    banner?:
                      | T
                      | {
                          image?: T;
                          imageUrl?: T;
                          alt?: T;
                          href?: T;
                          id?: T;
                          blockName?: T;
                        };
                    cta?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                          buttonLabel?: T;
                          buttonUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    slider?:
                      | T
                      | {
                          slides?:
                            | T
                            | {
                                image?: T;
                                imageUrl?: T;
                                alt?: T;
                                href?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    content?:
                      | T
                      | {
                          body?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          media?: T;
                          imageUrl?: T;
                          alt?: T;
                          caption?: T;
                          id?: T;
                          blockName?: T;
                        };
                    formTabs?:
                      | T
                      | {
                          title?: T;
                          intro?: T;
                          tabs?: T;
                          privacyHref?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heading?:
                      | T
                      | {
                          text?: T;
                          anchorId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    fileList?:
                      | T
                      | {
                          sectionTitle?: T;
                          items?:
                            | T
                            | {
                                title?: T;
                                file?: T;
                                fileUrl?: T;
                                fileExt?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    embed?:
                      | T
                      | {
                          title?: T;
                          html?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              column6?:
                | T
                | {
                    hero?:
                      | T
                      | {
                          heading?: T;
                          subtitle?: T;
                          image?: T;
                          imageUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    banner?:
                      | T
                      | {
                          image?: T;
                          imageUrl?: T;
                          alt?: T;
                          href?: T;
                          id?: T;
                          blockName?: T;
                        };
                    cta?:
                      | T
                      | {
                          title?: T;
                          text?: T;
                          buttonLabel?: T;
                          buttonUrl?: T;
                          id?: T;
                          blockName?: T;
                        };
                    slider?:
                      | T
                      | {
                          slides?:
                            | T
                            | {
                                image?: T;
                                imageUrl?: T;
                                alt?: T;
                                href?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    content?:
                      | T
                      | {
                          body?: T;
                          id?: T;
                          blockName?: T;
                        };
                    image?:
                      | T
                      | {
                          media?: T;
                          imageUrl?: T;
                          alt?: T;
                          caption?: T;
                          id?: T;
                          blockName?: T;
                        };
                    formTabs?:
                      | T
                      | {
                          title?: T;
                          intro?: T;
                          tabs?: T;
                          privacyHref?: T;
                          id?: T;
                          blockName?: T;
                        };
                    heading?:
                      | T
                      | {
                          text?: T;
                          anchorId?: T;
                          id?: T;
                          blockName?: T;
                        };
                    fileList?:
                      | T
                      | {
                          sectionTitle?: T;
                          items?:
                            | T
                            | {
                                title?: T;
                                file?: T;
                                fileUrl?: T;
                                fileExt?: T;
                                id?: T;
                              };
                          id?: T;
                          blockName?: T;
                        };
                    embed?:
                      | T
                      | {
                          title?: T;
                          html?: T;
                          id?: T;
                          blockName?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  generateSlug?: T;
  slug?: T;
  publishedAt?: T;
  thumbnail?: T;
  thumbnailUrl?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  galleryUrls?:
    | T
    | {
        url?: T;
        alt?: T;
        id?: T;
      };
  content?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "achievements_select".
 */
export interface AchievementsSelect<T extends boolean = true> {
  order?: T;
  title?: T;
  year?: T;
  image?: T;
  imageUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  formType?: T;
  name?: T;
  phone?: T;
  email?: T;
  subject?: T;
  message?: T;
  pageSlug?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headerNav".
 */
export interface HeaderNav {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        children?:
          | {
              label: string;
              href: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerNav".
 */
export interface FooterNav {
  id: number;
  items?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerContent".
 */
export interface FooterContent {
  id: number;
  navSectionTitle?: string | null;
  contactsSectionTitle?: string | null;
  contactsBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  extraBody?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  copyrightOrganization?: string | null;
  busBadgeImageUrl?: string | null;
  busBadgeImageAlt?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homeSlider".
 */
export interface HomeSlider {
  id: number;
  slides?:
    | {
        image?: (number | null) | Media;
        /**
         * Альтернатива upload — прямой URL.
         */
        imageUrl?: string | null;
        alt?: string | null;
        href?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "headerNav_select".
 */
export interface HeaderNavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        children?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerNav_select".
 */
export interface FooterNavSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footerContent_select".
 */
export interface FooterContentSelect<T extends boolean = true> {
  navSectionTitle?: T;
  contactsSectionTitle?: T;
  contactsBody?: T;
  extraBody?: T;
  copyrightOrganization?: T;
  busBadgeImageUrl?: T;
  busBadgeImageAlt?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homeSlider_select".
 */
export interface HomeSliderSelect<T extends boolean = true> {
  slides?:
    | T
    | {
        image?: T;
        imageUrl?: T;
        alt?: T;
        href?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}